# Generated by Django 5.0.6 on 2024-06-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0004_alter_musician_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument_type',
            field=models.CharField(choices=[('STRING', 'String'), ('WOODWIND', 'Woodwind'), ('KEYBOARD', 'Keyboard')], default=None, max_length=100),
        ),
    ]
